# Современные методы анализа данных и машинного обучения, БИ

## НИУ ВШЭ, 2023-24 учебный год

### Домашнее задание №1. Библиотеки Numpy & Pandas

Задание выполнил(а):

    (впишите свои фамилию и имя)

### Общая информация

__Дата выдачи:__ 09.02.2024

__Дедлайн:__ 04:00 19.02.2024

### Оценивание и штрафы

Каждая задача первого раздела (Numpy) оценивается в 2 балла.

Оценка за первый раздел вычисляется по следующей формуле:

$$
s_{\text{numpy}} \times 1/2 ,
$$

где $s_{\text{numpy}}$  — количество баллов, которое вы набрали в сумме по задачам первого раздела.

Каждая задача второго раздела (Pandas) оценивается в 3 балла.

Оценка за второй раздел вычисляется по следующей формуле:

$$
s_{\text{pandas}} \times 10/54 ,
$$

где $s_{\text{pandas}}$  — количество баллов, которое вы набрали в сумме по задачам второго раздела.

Общая оценка за ДЗ вычисляется по следующей формуле:

$$
O_{1} \times 3/10 + O_2 \times 7/10 ,
$$

где $O_1, O_2$  — оценки за первый и второй раздел соответственно.

За сдачу задания позже срока на итоговую оценку за задание накладывается штраф в размере 1 **вторичный** балл в день, но  задержка не может быть больше недели.

**Важно:** В этом домашнем задании предусмотрено несколько заданий, за которые можно получить бонусные баллы. Бонусные баллы прибавляются к обычным баллам, и может выйти так, что ваша итоговая оценка станет больше 10. В таком случае именно это и будет являться вашей оценкой. То есть за это ДЗ **можно** получить больше 10

__Внимание!__ Домашнее задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов.

### Формат сдачи

Загрузка файлов с решениями происходит в системе [Anytask](https://anytask.org/). Необходимо загружать файл с расширением .ipynb (питоновский ноутбук)

Инвайт для подключения к странице курса в системе — будет указан для каждой группы в нашем телеграмм-канале

## Раздел 1. Numpy

### О задании

В данном разделе вы попрактикуетесь в работе с библиотекой numpy!

In [1]:
import numpy as np

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

### 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.32, вес домашек - 0.28, вес групповых проектов - 0.12, вес аудиторки - 0.14, вес контрольной - 0.14. Например, если экзамен написан на 6, домашки сданы на 9, проекты закрыты на 8, оценка за аудиторку 7, а контрольная написана на 10 - итоговая оценка будет хорошо - 7

In [2]:
def result_mark(weights, marks):
    return int(np.around(np.average(marks,   weights = weights)))

In [3]:
weights = np.array([0.32, 0.18, 0.12, 0.14, 0.14])
marks = np.array([6, 9, 8, 7, 10])
result_mark(weights, marks)

8

### 2

Напишите функцию, меняющую каждое третье (начиная с 0) значение массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([-111, 5, 1, -111, -3, 22, -111])`.

In [4]:
def change_array(array, number):
    array[0:len(array):3]=number
    return array

In [5]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

array([-111,    5,    1, -111,   -3,   22, -111])

### 3

Напишите функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. Например, если на вход поступают массив `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, массив `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` и число `0.5`, то на выходе должен получиться массив `array([0, 1, 3, 6])` (_**важно: не `tuple`, а одномерный массив типа `numpy.ndarray` (то есть `.ndim` от него равно 1)!**_).

In [6]:
def find_close(array1, array2, precision):
    count=0
    array3 = array1-array2
    array3[array3==precision+1] = precision+2
    print(array3)
    array3[abs(array3) <= precision] = precision+1
    i=np.where(array3==precision+1)
    i=np.asarray(i)
    i=i.astype('int')
    k=i[0]
    return k

In [7]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)

[ 0.3  0.   1.  -0.1 -6.   6.   0.2]


array([0, 1, 3, 6])

### 4

Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
\end{pmatrix},
$$
то ответом будет матрица
$$
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
\end{pmatrix}
$$

In [8]:
def block_matrix(block):
    k=np.tile(block, 2)
    e=k.copy()
    p=np.concatenate([e,k])
    return p

In [9]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

In [10]:
def diag_prod(matrix):
    array1 = matrix.diagonal()
    array2 = array1[array1 != 0]
    mult = np.multiply.reduce(array2)
    return mult

In [11]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32

### 6

Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать [нормализацию данных](https://vk.cc/8xmfQk), чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам). Например, если на вход подается матрица
$$
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
$$
то результатом с точностью до сотых будет матрица
$$
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}
$$

_Подсказка. Учтите, что в вашей матрице не должно получаться никаких nan. Подумайте, в каком случае они могут возникнуть и как обойти эту проблему._


In [12]:
def normalize(matrix):
    matrix=matrix.T
    k=np.mean(matrix, axis=1, keepdims=True)
    e=(matrix-k)**2
    p=np.sum(e, axis=1, keepdims=True)
    z=np.divide(p, len(matrix[0]))
    z = np.sqrt(z)
    res=matrix-k
    answ=res/z
    answ=answ.T
    answ=np.around(answ, decimals=2)
    return answ

In [13]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize(matrix)

array([[ 0.71, -0.39,  0.46],
       [-1.41,  1.37,  0.93],
       [ 0.71, -0.98, -1.39]])

### 7

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

In [16]:
def antiderivative(coefs):
    p = np.polyint(coefs)
    #Чтобы не брать константу за любимое число, пусть она остается нулем, 0 - любимое число, дырка от бублика
    return p

In [17]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([1., 2., 0., 1., 0.])

### 8

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

In [18]:
def make_symmetric(matrix):
    p=matrix.copy()
    e=np.diagonal(p)
    e.setflags(write = True)
    e[e!=0]=0
    
    res=p+matrix.T
    return res

In [19]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

### 9

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

In [20]:
def construct_matrix(m, a, b):
    matrix=np.arange(a, b+1)
    d = np.full((m, abs(b-a+1)), 7)
    d[0:]=matrix
    return d

In [21]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

array([[ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

### 10

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

In [22]:
def cosine_similarity(vec1, vec2):
    p=vec1*vec2
    k=p.sum()
    e1=vec1**2
    e2=vec2**2
    len1=(e1.sum())**0.5
    len2=(e2.sum())**0.5
    res=k/(len1*len2)
    return res

In [23]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25

## Раздел 2. Pandas

### О задании

В данном разделе вы попрактикуетесь в работе с библиотекой pandas!

In [24]:
import pandas as pd

Обратите внимание, что практически во всех заданиях вам потребуется написать какой-то текст в виде вывода/результата/итога/какого-то резюме. Пожалуйста, не ленитесь, и пишите выводы ***подробно***, существенная часть баллов будет выставляться именно за выводы, так как в анализе данных они имеют большое значение. Таким образом, на любое задание, сформулированное в виде вопроса, отвечайте текстом, подкрепляя ваши слова написанным и выполненным кодом. Текст выводов/комментариев пишите в отдельных ячейках, используя средства текстового редактора Jupyter Notebook/Google Colab, при необходимости используйте средства *выделения*.

При решении задач, когда вам необходимо сделать какой-то фильтр, срез, выборку, или иное действие с данными, запрещается использовать циклы (`for`, `while`) и оператор `if`.


### 1

В этом разделе домашнего задания вы поработаете с данными исследования зависимости средней продолжительности жизни по странам от количества употребляемого в стране алкоголя.

Вашему вниманию представлено два датасета: drinks.csv и lifeexpectancy-verbose.csv

Первая таблица содержит в себе сводные данные по количеству употребляемого алкоголя в каждой стране.

Описание датасета:
- country -	Name of the country (String)
- beer_servings	- Number of beer servings per person in the country (Integer)
- spirit_servings	- Number of spirit servings per person in the country (Integer)
- wine_servings	- Number of wine servings per person in the country(Integer)
- total_litres_of_pure_alcohol -	Total litres of pure alcohol consumed per person in the country (Float)

Вторая таблица содержит в себе информацию о научных статьях и исследованиях о продолжительности жизни (в разных категориях и для разных групп) по той или иной стране.

Откройте в ноутбуке оба файла с данными. Какой размер имеют таблицы? Выведите первые 5 и последние 5 строк для обеих таблиц. Сколько уникальных стран представлено в каждой из таблиц? Сделайте выводы.

In [139]:
df_drinks = pd.read_csv('drinks.csv')
df_life = pd.read_csv('lifeexpectancy-verbose.csv')

In [31]:
df_drinks.shape #То есть 193 строки, 6 столбцов

(193, 6)

In [32]:
df_life.shape #То есть 6408 строк, 17 столбцов

(6408, 17)

In [53]:
df_drinks.head()

index      country  beer_servings  spirit_servings  wine_servings  \
0      0  Afghanistan              0                0              0   
1      1      Albania             89              132             54   
2      2      Algeria             25                0             14   
3      3      Andorra            245              138            312   
4      4       Angola            217               57             45   

   total_litres_of_pure_alcohol  
0                           0.0  
1                           4.9  
2                           0.7  
3                          12.4  
4                           5.9

In [54]:
df_life.head()

index        GhoCode                                       GhoDisplay  \
0      0  WHOSIS_000001                 Life expectancy at birth (years)   
1      1  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
2      2  WHOSIS_000001                 Life expectancy at birth (years)   
3      3  WHOSIS_000001                 Life expectancy at birth (years)   
4      4  WHOSIS_000015                Life expectancy at age 60 (years)   

  PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
0        PUBLISHED           Published      1990         1990        AMR   
1        PUBLISHED           Published      2012         2012        EUR   
2        PUBLISHED           Published      2000         2000        EMR   
3        PUBLISHED           Published      2000         2000        AFR   
4        PUBLISHED           Published      1990         1990       SEAR   

           RegionDisplay WorldBankIncomeGroupGroupCode  \
0               Americas                        WB_LMI   
1                 Europe                         WB_HI   
2  Eastern Mediterranean                         WB_LI   
3                 Africa                        WB_LMI   
4        South_East Asia                        WB_LMI   

  WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  SexDisplay  \
0         Lower_middle_income         NIC      Nicaragua     MLE        Male   
1                 High_income         IRL        Ireland     MLE        Male   
2                  Low_income         YEM          Yemen    BTSX  Both sexes   
3         Lower_middle_income         NGA        Nigeria    FMLE      Female   
4         Lower_middle_income         THA       Thailand    FMLE      Female   

   DisplayValue  Numeric  
0            68     68.0  
1            69     69.3  
2            61     61.0  
3            48     48.0  
4            19     19.0

In [55]:
df_drinks.tail()

index    country  beer_servings  spirit_servings  wine_servings  \
188    188  Venezuela            333              100              3   
189    189    Vietnam            111                2              1   
190    190      Yemen              6                0              0   
191    191     Zambia             32               19              4   
192    192   Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol  
188                           7.7  
189                           2.0  
190                           0.1  
191                           2.5  
192                           4.7

In [56]:
df_life.tail()

index        GhoCode                                       GhoDisplay  \
6403   6403  WHOSIS_000001                 Life expectancy at birth (years)   
6404   6404  WHOSIS_000015                Life expectancy at age 60 (years)   
6405   6405  WHOSIS_000001                 Life expectancy at birth (years)   
6406   6406  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
6407   6407  WHOSIS_000001                 Life expectancy at birth (years)   

     PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
6403        PUBLISHED           Published      2000         2000        EMR   
6404        PUBLISHED           Published      1990         1990        WPR   
6405        PUBLISHED           Published      1990         1990        AFR   
6406        PUBLISHED           Published      2012         2012        EUR   
6407        PUBLISHED           Published      2013         2013        EUR   

              RegionDisplay WorldBankIncomeGroupGroupCode  \
6403  Eastern Mediterranean                        WB_LMI   
6404        Western Pacific                        WB_UMI   
6405                 Africa                         WB_LI   
6406                 Europe                        WB_LMI   
6407                 Europe                           NaN   

     WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  \
6403         Lower_middle_income         MAR        Morocco    BTSX   
6404         Upper_middle_income         PLW          Palau    BTSX   
6405                  Low_income         BFA   Burkina Faso    FMLE   
6406         Lower_middle_income         ALB        Albania     MLE   
6407                         NaN         ARM        Armenia    BTSX   

      SexDisplay  DisplayValue   Numeric  
6403  Both sexes            68  68.00000  
6404  Both sexes            16  16.00000  
6405      Female            51  51.00000  
6406        Male            64  63.50000  
6407  Both sexes            71  71.02699

In [62]:
df_drinks['country'].nunique()

193

In [63]:
df_life['CountryCode'].nunique()

194

Вывод: Данные в df_life - сырые, многие столбцы дублируют сами себя и только перегружают таблицу, что приводит к более трудному восприятию информации. Зато эти данные имеют более ценную для нас смысловую нагрузку. Данные в df_drinks более укомпанованы и с ними работать будет легче. Если говорить про взаимосвязь между двумя таблицами, то в них указано почти одинаковое кол-во уникальных городов, что в дальнейшем можно будет связать продолжительность жизни с количеством выпитого алкоголя в стране.

### 2

Для каждого признака в рассматриваемых данных укажите тип этого признака и кратко обоснуйте, почему тип именно такой. Тут под номинальным я имел в виду категориальный, т.к в Вики это называется номинальным.

Тип признаков в df_drinks:  
index - Порядковый (указывает номер строки)  
country - Номинальный (название страны)  
beer_servings - Количественный (количесвто порций пива на человека)  
spirit_servings - аналогично пиву  
wine_servings - аналогично пиву  
total_litres_of_pure_alcohol - количественный (кол-во литров алкоголя, которая потребляет человек в стране)  
Тип признаков в df_life:  
index - Порядковый (указывает номер строки)  
GhoCode - номинальный (код, который обозначает конкретный показатель здоровья)  
GhoDisplay - номинальный (описание показателя здоровья, соответствующее GhoCode)  
PublishStateCode - номинальный (код, указывающий статус публикации данных)  
PublishStateDisplay - номинальный (код, указывающий статус публикации, аналогичен PublishStateCode)  
YearCode - Количественный (год, к которому относятся показатели)  
YearDisplay - Количественный (год, к которому относятся показатели)  
RegionCode - Номинальный (код региона)  
RegionDisplay - номинальный (расшифровка RegionCode, полное название региона)  
WorldBankIncomeGroupGroupCode - номинальный (код группы по доходу)  
WorldBankIncomeGroupDisplay - номинальный (расшифровка WorldBankIncomeGroupGroupCode)  
CountryCode - номинальный (код страны)  
CountryDisplay - номинальный (расшифровка CountryCode)  
SexCode - номинальный (пол, к которому относится)  
SexDisplay - номинальный (расшифровка SexCode)  
DisplayValue - количественный (значение продолжительности жизни int)  
Numeric - количественный (значение прололжительности жизни float)  

### 3

Внимательно изучите признаки обеих таблиц. Как вы считаете, какая из таблиц является главной (а какая сопутствующей)? Почему вы так думаете?

Какой признак может представлять существенный интерес для исследования и являться целевой переменной в рамках представленного датасета? Ответ обоснуйте.

***Бонус (1 бон. балл):*** Попробуйте описать задачу машинного обучения, которую вы могли бы решать для данного датасета с учетом выбранной вами раннее целевой переменной и проблематики исследования. Подробнее про постановку и формализацию задач машинного обучения, а также про различные типы таких задач — вы можете прочитать, например, вот в этой [статье](https://habr.com/ru/company/simbirsoft/blog/565396/) (в начале)

Главной таблицей является life, тк в ней находится наиболее ценная для нас информация. Имеется много столбцов, которые описывают различные показатели, такие как: достаток человека, пол, страна проживания. Мы сможем разбить пользователей на различные выборки и сгруппировать их по различным признакам. Это является наиболее ценной для нас информацией. Таблица про алкоголь будет сопуствующей, она поможет объяснить, почему именно такие цифры содержатся в основной таблице. То есть благодаря ней мы сможем провести исследование, как алкоголь влияет на продолжительность жизни.  
Целевой метрикой для нас будет являться GhoDisplay (если говорить прос столбец), а скорее даже показатель Life Expectancy at birth, то есть берем этот столбец и смотрим значение в Numeric (Значение метрики). Данная метрика сможет отражать многие факторы, влияющие на продолжительность жизни: доступность медицины для населения, экологическая ситуация в стране, половой признак и другое. То есть мы будем исследовать как данная метрика меняется от различных факторов. Как алкоголь и другие факторы влияют на продолжительность жизни человека.
Бонус. Задача машинного обучения будет заключаться в восстановлении регресии (прогнозирования). То есть регрессия продолжительности жизни на основе вляиния социально-экономических признаков. Цель машинного обучения - научиться предсказывать продолжительность жизни на основе входных данных, таких как: пол, возраст, страна, кол-во алкоголя, достаток. Точность модели мы сможем измерять с помощью метрики MSE - среднеквадратическая ошибка (мы такого не проходили :))

### 4

Какова доля статей о продолжительности жизни в Африке? Какова доля статей о продолжительности жизни мужчин и доля статей о продолжительности жизни женщин среди всех статей по Африке?

***Бонус (2 бон. балла):*** Сравните эти доли с аналогичными долями по другим регионам. Как вы можете объяснить возникающие сходства и различия? Прокомментируйте полученные результаты.

In [81]:
total_articles = df_life.shape[0]
about_africa = df_life[df_life['RegionDisplay'] == 'Africa'].shape[0]
share_africa = about_africa / total_articles
round(share_africa, 4) #Доля статей о продолжительнсоти жизни в Африке

0.2378

In [80]:
about_males = df_life[(df_life['RegionDisplay'] == 'Africa') & (df_life['SexDisplay'] == 'Male')].shape[0]
about_females = df_life[(df_life['RegionDisplay'] == 'Africa') & (df_life['SexDisplay'] == 'Female')].shape[0]
share_males = about_males / about_africa
share_females = about_females / about_africa
print(f'''Доля статей об Африке - {share_africa}\nДоля статей в Африке о мужчинах - {share_males}\nДоля статей в Африке о женщинах - {share_females}''')

Доля статей об Африке - 0.23782771535580524
Доля статей в Африке о мужчинах - 0.3333333333333333
Доля статей в Африке о женщинах - 0.3333333333333333


In [84]:
articles_region = df_life['RegionDisplay'].value_counts()

In [89]:
import matplotlib.pyplot as plt

In [94]:
articles_region.plot(kind='pie', figsize=(10, 6) ,autopct='%1.1f%%', startangle=140)
plt.title('Доля статей на регион')
plt.ylabel('') 
plt.show()

Как мы видим, что наибольшую долю статей занимает Европа, т.к данный регион является лидирующим в развитии здравоохранении, поэтому и большиство статей были написаны в нем. Африка занимает второе место, потому что около 11 миллионов африканцев переходят черту крайней нищеты, и более развитые страные стараются поддерживать данный регион. Также Африка явлется довольно интересным объектом исследования, т.к жизнь в этом регионе сильно отличается от привычного нам. Америка отстает от Европы на 9 процентных пунктов. Доволньо интересное наблюдение, т.к население во всей Америке больше на 300 млн человек, чем население всей Европы и Америка вкладывает 18% ВВП в медицину.

### 5

Сколько всего существует видов статей с точки зрения оцениваемого параметра продолжительности жизни? Какой из этих видов статей самый популярный (написано наибольшее количество научных работ)? В рамках найденного вами самого популярного вида статей проведите сравнение, относительно какой из половых групп: мужчины, женщины или же оба пола — статей в нем было больше всего?

In [96]:
total_articles_gho = df_life['GhoDisplay'].value_counts()
total_articles_gho

Life expectancy at birth (years)                   2328
Life expectancy at age 60 (years)                  2328
Healthy life expectancy (HALE) at birth (years)    1752
Name: GhoDisplay, dtype: int64

У нас получилось, что у двух групп: продолжительность жизни в 60 лет и продолжительность жизни с рождения написано одинаковое количество статей - 2328. Наиболее интересный для меня предмет исследования - Life expectancy at birth (years), т.к он указывает на продолжительность жизни при рождении человека.

In [99]:
popular_gho_sex = df_life[df_life['GhoDisplay'] == 'Life expectancy at birth (years)']['SexDisplay'].value_counts()
popular_gho_sex

Male          776
Both sexes    776
Female        776
Name: SexDisplay, dtype: int64

Как мы видим распределение статей по половым признаком - равномерное, т.к содержит одинаковое кол-во статей в каждой группе - 776.

### 6

Выведите минимальную, среднюю, медианную и максимальную оцененную продолжительность жизни людей от рождения (life expectancy at birth). Выберите любые три страны на ваш вкус и проделайте то же самое только для статей по этим странам. Что можно сказать на основе результатов, которые вы получили?

In [106]:
min_expect_birth = df_life[df_life['GhoDisplay'] == 'Life expectancy at birth (years)']['Numeric'].min()
mean_expect_birth = df_life[df_life['GhoDisplay'] == 'Life expectancy at birth (years)']['Numeric'].mean()
median_expect_birth = df_life[df_life['GhoDisplay'] == 'Life expectancy at birth (years)']['Numeric'].median()
max_expect_birth = df_life[df_life['GhoDisplay'] == 'Life expectancy at birth (years)']['Numeric'].max()
print(f'''Минимальная - {min_expect_birth}\n
Средняя продолжительность - {mean_expect_birth}\n
Медиана - {median_expect_birth}\n
Максимальная - {max_expect_birth}\n
''')

Минимальная - 38.0

Средняя продолжительность - 68.44137943298968

Медиана - 70.857895

Максимальная - 87.15457




In [115]:
countries = ['Nigeria', 'Germany', 'Canada']
countries_res = df_life[df_life['CountryDisplay'].isin(countries)].groupby('CountryDisplay')['Numeric'].agg(['min', 'mean', 'median', 'max'])
countries_res

min       mean  median       max
CountryDisplay                                   
Canada          19.0  57.131743    71.8  84.01681
Germany         18.0  55.954190    71.0  83.27878
Nigeria         14.0  36.071809    46.0  55.40039

Как мы видим, что значения в Германии и в Канаде довольно похожие, что можно увидеть по медиане, которая учитывает выбросы выборки. В Нигерии медиана ниже на 64,7%, что говорит о низком уровне жизни в странах Африки, а максимальная продолжительность жизни в Нигерии всего 55 лет, что удивиетельно.

### 7

Сформируйте результирующий датафрейм на основе проделанных вами действий в предыдущем номере. У датафрейма должно быть 4 столбца, в соответствии с заданными агреггирующими функциями: минимум, среднее, медиана, максимум, — а также 4 строки: статистика по всему датасету; статистика по трем выбранным вами странам. Сохраните программно созданный вами датафрейм в виде csv файла.

*Примечание. Датафрейм необходимо создавать автоматизированным образом. Не допускается ручной перенос значений из полученных в предыдущем задании ячеек в пустой датафрейм и/или прописывание конкретных значений (чисел) в коде программы. Представьте, что у нас не 3 страны, а 100 и не 4 агреггирующих метрики, а 100!*

Случайно сделал это в предыдущем задании, что меня очень сильно порадовало в час ночи, т.к заданий стало на одно меньше, а усилий я не приложил, осталось только сохранить его в csv файл, что я и сделаю :))))

In [116]:
countries_res.to_csv('stats_countries')

### 8

Есть ли в наших датасетах пропуски? Если да, то в каких столбцах? Сколько пропусков в каждом из них?

Подумайте, как стоит избавиться от пропусков в каждом из столбцов, и сделайте это. Аргументируйте ваши действия.

Проверьте, что пропусков нигде не осталось.

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с уже обновленными датасетами.*

In [126]:
count_null_life = df_life.isnull().sum()
count_null_life

index                               0
GhoCode                             0
GhoDisplay                          0
PublishStateCode                    0
PublishStateDisplay                 0
YearCode                            0
YearDisplay                         0
RegionCode                          0
RegionDisplay                       0
WorldBankIncomeGroupGroupCode    1164
WorldBankIncomeGroupDisplay      1164
CountryCode                         0
CountryDisplay                      0
SexCode                             0
SexDisplay                          0
DisplayValue                        0
Numeric                             0
dtype: int64

In [127]:
count_null_drinks = df_drinks.isnull().sum()
count_null_drinks

index                           0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
dtype: int64

В датасете df_drinks пропусков - нет  
В датасете df_life есть одинаковое количество пропусков в 1164 строках в столбцах WorldBankIncomeGroupGroupCode и WorldBankIncomeGroupDisplay, т.к они отображают одно и тоже (писал выше)  
Всего у нас 6408 строк, из них 1164 - пропуски по колонке дохода, так что удалять значения будет не особо честно, так как это почти 20% всей выборки. Поэтому заполним их просто значением 'Unknown', показав, что данные об этих исследованиях нам неизвестны.

In [128]:
df_life.fillna('Unknown', inplace=True)

In [129]:
count_null_life = df_life.isnull().sum()
count_null_life

index                            0
GhoCode                          0
GhoDisplay                       0
PublishStateCode                 0
PublishStateDisplay              0
YearCode                         0
YearDisplay                      0
RegionCode                       0
RegionDisplay                    0
WorldBankIncomeGroupGroupCode    0
WorldBankIncomeGroupDisplay      0
CountryCode                      0
CountryDisplay                   0
SexCode                          0
SexDisplay                       0
DisplayValue                     0
Numeric                          0
dtype: int64

Как видим пропусков стало ноль.

### 9

Все ли признаки несут в себе полезную информацию? Почему вы так считаете? Избавьтесь от ненужных столбцов. Свой выбор аргументируйте

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с уже обновленными датасетами.*

Не все признаки несут в себе полезную информацию. Как я писал ранее некоторые колонки дублируют друг друга, например: PublishStateCode-PublishStateDisplay,	YearCode-YearDisplay, DisplayValue-Numeric.  
Также есть столбцы, которые отражают код и название, в принципе названия будет достаточно или кода, так что можно один из столбцов оставить, а второй - убрать.

In [147]:
df_life_new = df_life.drop(['GhoCode', 'PublishStateCode', 'YearCode', 'RegionCode', 'WorldBankIncomeGroupGroupCode', 'CountryCode', 'SexCode', 'DisplayValue'], axis = 1)


In [148]:
df_life_new.head()

index                                       GhoDisplay PublishStateDisplay  \
0      0                 Life expectancy at birth (years)           Published   
1      1  Healthy life expectancy (HALE) at birth (years)           Published   
2      2                 Life expectancy at birth (years)           Published   
3      3                 Life expectancy at birth (years)           Published   
4      4                Life expectancy at age 60 (years)           Published   

   YearDisplay          RegionDisplay WorldBankIncomeGroupDisplay  \
0         1990               Americas         Lower_middle_income   
1         2012                 Europe                 High_income   
2         2000  Eastern Mediterranean                  Low_income   
3         2000                 Africa         Lower_middle_income   
4         1990        South_East Asia         Lower_middle_income   

  CountryDisplay  SexDisplay  Numeric  
0      Nicaragua        Male     68.0  
1        Ireland        Male     69.3  
2          Yemen  Both sexes     61.0  
3        Nigeria      Female     48.0  
4       Thailand      Female     19.0

### 10

Посчитайте, насколько сильно коррелируют друг с другом потребления разных видов алкоголя (beer_servings,	spirit_servings и	wine_servings). Создайте датафрейм с попарными корреляциями этих столбцов друг с другом. Какие выводы можно сделать?

In [152]:
drinks_correlations = df_drinks[['beer_servings', 'spirit_servings', 'wine_servings']].corr()
drinks_correlations

beer_servings  spirit_servings  wine_servings
beer_servings         1.000000         0.458819       0.527172
spirit_servings       0.458819         1.000000       0.194797
wine_servings         0.527172         0.194797       1.000000

Мы видим, что пиво лучше всего коррелирует со всеми остальными алкогольными напитками. Люди, склонные употрлеблять вино редко употребляют крепкие алкогольные напитки

### 11

Каким образом следует осуществить соединение двух имеющихся у нас таблиц? Почему? Соедините таблицы!

Получилось ли у вас задействовать все строки, и если нет, то почему? Что делать с теми строками, которые не удается задействовать, если таковые есть? Ответ обоснуйте.

*Подсказка. В ответе на первый вопрос задания, а также в обосновании способа соединения таблиц вам может помочь задание 3 данного раздела ДЗ и соответствующий семинарский ноутбук!*

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с одним объединенным датасетом.*

In [156]:
df_together = pd.merge(left=df_life_new, right=df_drinks, how='left', left_on='CountryDisplay', right_on='country')
df_together.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6408 entries, 0 to 6407
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   index_x                       6408 non-null   int64  
 1   GhoDisplay                    6408 non-null   object 
 2   PublishStateDisplay           6408 non-null   object 
 3   YearDisplay                   6408 non-null   int64  
 4   RegionDisplay                 6408 non-null   object 
 5   WorldBankIncomeGroupDisplay   5244 non-null   object 
 6   CountryDisplay                6408 non-null   object 
 7   SexDisplay                    6408 non-null   object 
 8   Numeric                       6408 non-null   float64
 9   index_y                       5511 non-null   float64
 10  country                       5511 non-null   object 
 11  beer_servings                 5511 non-null   float64
 12  spirit_servings               5511 non-null   float64
 13  win

Мы делаем лефт джоин, чтобы из основной таблицы не потерялись никакие данные, но как мы видим некоторые колонки - не полностью заполнены, то есть не по всем странам есть информация. Как мы видели в начале исследования, в одном датасете было 163 страны, а в другом - 164.

### 12

Осуществите группировку данных по странам и типу научной статьи (многомерная группировка). В качестве столбцов значений для группировки возьмите оцененную продолжительность жизни и общее потребление алкоголя в литрах. В качестве агреггирующих функций для продолжительности жизни возьмите среднее, медиану, минимум и максимум, а для потребления алкоголя — агреггирующую функцию/функции выберите самостоятельно. Как вы можете прокомментировать свой выбор и что вы наблюдаете?

In [160]:
info_group = df_together.groupby(['CountryDisplay', 'GhoDisplay']).agg({
    'Numeric': ['mean', 'median', 'min', 'max'],  
    'total_litres_of_pure_alcohol': ['mean']  
})
info_group.head(30)

Numeric  \
                                                                          mean   
CountryDisplay      GhoDisplay                                                   
Afghanistan         Healthy life expectancy (HALE) at birth (years)  47.833333   
                    Life expectancy at age 60 (years)                15.223012   
                    Life expectancy at birth (years)                 56.311805   
Albania             Healthy life expectancy (HALE) at birth (years)  63.800000   
                    Life expectancy at age 60 (years)                17.728610   
                    Life expectancy at birth (years)                 71.871584   
Algeria             Healthy life expectancy (HALE) at birth (years)  61.622222   
                    Life expectancy at age 60 (years)                17.635895   
                    Life expectancy at birth (years)                 70.216262   
Andorra             Healthy life expectancy (HALE) at birth (years)  70.966667   
                    Life expectancy at age 60 (years)                23.884953   
                    Life expectancy at birth (years)                 80.576820   
Angola              Healthy life expectancy (HALE) at birth (years)  42.444444   
                    Life expectancy at age 60 (years)                14.931843   
                    Life expectancy at birth (years)                 47.852151   
Antigua and Barbuda Healthy life expectancy (HALE) at birth (years)  64.066667   
                    Life expectancy at age 60 (years)                20.382623   
                    Life expectancy at birth (years)                 73.595177   
Argentina           Healthy life expectancy (HALE) at birth (years)  66.077778   
                    Life expectancy at age 60 (years)                20.768218   
                    Life expectancy at birth (years)                 74.903068   
Armenia             Healthy life expectancy (HALE) at birth (years)  62.355556   
                    Life expectancy at age 60 (years)                16.897574   
                    Life expectancy at birth (years)                 70.046697   
Australia           Healthy life expectancy (HALE) at birth (years)  71.733333   
                    Life expectancy at age 60 (years)                23.672306   
                    Life expectancy at birth (years)                 80.647330   
Austria             Healthy life expectancy (HALE) at birth (years)  69.855556   
                    Life expectancy at age 60 (years)                22.507437   
                    Life expectancy at birth (years)                 78.901652   

                                                                                \
                                                                        median   
CountryDisplay      GhoDisplay                                                   
Afghanistan         Healthy life expectancy (HALE) at birth (years)  48.800000   
                    Life expectancy at age 60 (years)                15.061535   
                    Life expectancy at birth (years)                 57.000000   
Albania             Healthy life expectancy (HALE) at birth (years)  63.900000   
                    Life expectancy at age 60 (years)                18.000000   
                    Life expectancy at birth (years)                 72.910505   
Algeria             Healthy life expectancy (HALE) at birth (years)  61.700000   
                    Life expectancy at age 60 (years)                17.933450   
                    Life expectancy at birth (years)                 70.125475   
Andorra             Healthy life expectancy (HALE) at birth (years)  71.700000   
                    Life expectancy at age 60 (years)                23.500000   
                    Life expectancy at birth (years)                 80.500000   
Angola              Healthy life expectancy (HALE) at birth (years)  43.300000   
                    Life expectancy at age 60 (years

В данном исследовании мы вообще не можем брать никакую агрегирующую функцию для общего кол-ва выпитого алкоголя, потому что у нас и так данные сгруппированы по странам изначально в датасете df_drinks и они уникальны по каждой стране, но пусть эта функция будет mean. Как мы видим, что не наблюдается никакой прямой зависимости от количества выпитого алкоголя и медианной продолжительности жизни.

Как раз одной страны, которой нет - это Antigua and Barbuda, вот она и нашлась :)))

### 13

Вставьте любые два столбца из предыдущего задания, которые вы получили путем группировки, в исходную таблицу в качестве двух новых столбцов (назвать вы их можете как хотите). Разумеется, значения этих столбцов должны соответствовать значениям исходной таблицы по указанным в прошлом задании категориям.

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с обновленным датасетом.*

In [162]:
df_final = pd.merge(df_together, info_group, on=['CountryDisplay', 'GhoDisplay'], how='left')
df_final.head()

C:\Users\barzd\AppData\Local\Temp\ipykernel_1136\3109475016.py:1: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (1 levels on the left, 2 on the right)
  df_final = pd.merge(df_together, info_group, on=['CountryDisplay', 'GhoDisplay'], how='left')


index_x                                       GhoDisplay  \
0        0                 Life expectancy at birth (years)   
1        1  Healthy life expectancy (HALE) at birth (years)   
2        2                 Life expectancy at birth (years)   
3        3                 Life expectancy at birth (years)   
4        4                Life expectancy at age 60 (years)   

  PublishStateDisplay  YearDisplay          RegionDisplay  \
0           Published         1990               Americas   
1           Published         2012                 Europe   
2           Published         2000  Eastern Mediterranean   
3           Published         2000                 Africa   
4           Published         1990        South_East Asia   

  WorldBankIncomeGroupDisplay CountryDisplay  SexDisplay  Numeric  index_y  \
0         Lower_middle_income      Nicaragua        Male     68.0    122.0   
1                 High_income        Ireland        Male     69.3     81.0   
2                  Low_income          Yemen  Both sexes     61.0    190.0   
3         Lower_middle_income        Nigeria      Female     48.0    124.0   
4         Lower_middle_income       Thailand      Female     19.0    169.0   

     country  beer_servings  spirit_servings  wine_servings  \
0  Nicaragua           78.0            118.0            1.0   
1    Ireland          313.0            118.0          165.0   
2      Yemen            6.0              0.0            0.0   
3    Nigeria           42.0              5.0            2.0   
4   Thailand           99.0            258.0            1.0   

   total_litres_of_pure_alcohol  (Numeric, mean)  (Numeric, median)  \
0                           3.5        72.667402               73.0   
1                          11.4        69.911111               69.8   
2                           0.1        61.567050               62.0   
3                           9.1        50.473338               50.5   
4                           6.4        19.895824               19.5   

   (Numeric, min)  (Numeric, max)  (total_litres_of_pure_alcohol, mean)  
0            68.0        76.62982                                   3.5  
1            65.7        72.60000                                  11.4  
2            56.0        65.70657                                   0.1  
3            45.0        55.40039                                   9.1  
4            16.0        23.14883                                   6.4

In [168]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6408 entries, 0 to 6407
Data columns (total 20 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   index_x                               6408 non-null   int64  
 1   GhoDisplay                            6408 non-null   object 
 2   PublishStateDisplay                   6408 non-null   object 
 3   YearDisplay                           6408 non-null   int64  
 4   RegionDisplay                         6408 non-null   object 
 5   WorldBankIncomeGroupDisplay           5244 non-null   object 
 6   CountryDisplay                        6408 non-null   object 
 7   SexDisplay                            6408 non-null   object 
 8   Numeric                               6408 non-null   float64
 9   index_y                               5511 non-null   float64
 10  country                               5511 non-null   object 
 11  beer_servings    

In [172]:
df_final.drop([('Numeric', 'max')], axis=1, inplace=True)


In [173]:
df_final.drop([('Numeric', 'min')], axis=1, inplace=True)
df_final.drop([('Numeric', 'mean')], axis=1, inplace=True)

In [174]:
df_final.head()

index_x                                       GhoDisplay  \
0        0                 Life expectancy at birth (years)   
1        1  Healthy life expectancy (HALE) at birth (years)   
2        2                 Life expectancy at birth (years)   
3        3                 Life expectancy at birth (years)   
4        4                Life expectancy at age 60 (years)   

  PublishStateDisplay  YearDisplay          RegionDisplay  \
0           Published         1990               Americas   
1           Published         2012                 Europe   
2           Published         2000  Eastern Mediterranean   
3           Published         2000                 Africa   
4           Published         1990        South_East Asia   

  WorldBankIncomeGroupDisplay CountryDisplay  SexDisplay  Numeric  index_y  \
0         Lower_middle_income      Nicaragua        Male     68.0    122.0   
1                 High_income        Ireland        Male     69.3     81.0   
2                  Low_income          Yemen  Both sexes     61.0    190.0   
3         Lower_middle_income        Nigeria      Female     48.0    124.0   
4         Lower_middle_income       Thailand      Female     19.0    169.0   

     country  beer_servings  spirit_servings  wine_servings  \
0  Nicaragua           78.0            118.0            1.0   
1    Ireland          313.0            118.0          165.0   
2      Yemen            6.0              0.0            0.0   
3    Nigeria           42.0              5.0            2.0   
4   Thailand           99.0            258.0            1.0   

   total_litres_of_pure_alcohol  (Numeric, median)  \
0                           3.5               73.0   
1                          11.4               69.8   
2                           0.1               62.0   
3                           9.1               50.5   
4                           6.4               19.5   

   (total_litres_of_pure_alcohol, mean)  
0                                   3.5  
1                                  11.4  
2                                   0.1  
3                                   9.1  
4                                   6.4

### 14

Используя группировки, аргументированно ответьте на вопрос: на каких континентах средняя ожидаемая продолжительность жизни выше у мужчин, а на каких у женщин?

А медианная ожидаемая продолжительность?

А минимальная ожидаемая продолжительность?

Сделайте выводы!

*Подсказка. Казалось бы, при чем здесь тип научной статьи?*

In [179]:
df_final_group = df_final.groupby(['RegionDisplay', 'SexDisplay'])['Numeric'].agg(['mean', 'median', 'min']).reset_index()


In [177]:
df_final_group.head(30)

RegionDisplay  SexDisplay       mean  median       min
0                  Africa  Both sexes  39.698243   46.00  11.00000
1                  Africa      Female  40.789563   47.00  11.00000
2                  Africa        Male  38.603784   45.25  11.00000
3                Americas  Both sexes  51.490027   63.30  15.00000
4                Americas      Female  53.630348   65.80  16.00000
5                Americas        Male  49.371465   61.20  12.86658
6   Eastern Mediterranean  Both sexes  47.574747   57.00  14.00000
7   Eastern Mediterranean      Female  48.714548   58.85  14.00000
8   Eastern Mediterranean        Male  46.565493   55.55  13.00000
9                  Europe  Both sexes  53.016106   65.90  15.00000
10                 Europe      Female  55.485740   69.00  16.00000
11                 Europe        Male  50.394290   63.00  12.00000
12        South_East Asia  Both sexes  46.639254   58.00  13.00000
13        South_East Asia      Female  48.077619   58.60  12.00000
14        South_East Asia        Male  45.178286   57.00  12.00000
15        Western Pacific  Both sexes  49.805079   61.00  13.00000
16        Western Pacific      Female  51.799305   63.00  15.00000
17        Western Pacific        Male  47.904163   58.90  12.00000

Как мы видим, что на всех континентах средняя продолжительность жизни у женщин больше, чем у мужчин. Это давно известный факт, что мужчины являются более склонны к риску (в прочем как и то, что мучжины чаще попадают в ДТП) и пытаются испытать все эмоции в жизни. Про медиану можно сказать тоже самое. Минимальная продолжительность жизни ни о чем не говорит, потому что часто происходят какие-то несчастные случаи в силу чего люди могут погибать довольно рано

Посмотрим на группировку по типу статьи: 

In [181]:
df_final_group_gho = df_final.groupby(['RegionDisplay', 'SexDisplay', 'GhoDisplay'])['Numeric'].agg(['mean', 'median', 'min']).reset_index()
df_final_group_gho.head(30)

RegionDisplay  SexDisplay  \
0                  Africa  Both sexes   
1                  Africa  Both sexes   
2                  Africa  Both sexes   
3                  Africa      Female   
4                  Africa      Female   
5                  Africa      Female   
6                  Africa        Male   
7                  Africa        Male   
8                  Africa        Male   
9                Americas  Both sexes   
10               Americas  Both sexes   
11               Americas  Both sexes   
12               Americas      Female   
13               Americas      Female   
14               Americas      Female   
15               Americas        Male   
16               Americas        Male   
17               Americas        Male   
18  Eastern Mediterranean  Both sexes   
19  Eastern Mediterranean  Both sexes   
20  Eastern Mediterranean  Both sexes   
21  Eastern Mediterranean      Female   
22  Eastern Mediterranean      Female   
23  Eastern Mediterranean      Female   
24  Eastern Mediterranean        Male   
25  Eastern Mediterranean        Male   
26  Eastern Mediterranean        Male   
27                 Europe  Both sexes   
28                 Europe  Both sexes   
29                 Europe  Both sexes   

                                         GhoDisplay       mean    median  \
0   Healthy life expectancy (HALE) at birth (years)  49.136232  49.35000   
1                 Life expectancy at age 60 (years)  16.110551  16.00000   
2                  Life expectancy at birth (years)  56.245705  57.00000   
3   Healthy life expectancy (HALE) at birth (years)  50.094203  50.00000   
4                 Life expectancy at age 60 (years)  16.792841  16.94181   
5                  Life expectancy at birth (years)  57.845527  58.00000   
6   Healthy life expectancy (HALE) at birth (years)  48.190580  48.80000   
7                 Life expectancy at age 60 (years)  15.331986  15.14800   
8                  Life expectancy at birth (years)  54.724349  55.00000   
9   Healthy life expectancy (HALE) at birth (years)  63.838095  63.80000   
10                Life expectancy at age 60 (years)  20.690960  21.00000   
11                 Life expectancy at birth (years)  73.028041  74.00000   
12  Healthy life expectancy (HALE) at birth (years)  65.971429  66.20000   
13                Life expectancy at age 60 (years)  22.131179  22.53821   
14                 Life expectancy at birth (years)  75.873706  77.00000   
15  Healthy life expectancy (HALE) at birth (years)  61.752381  62.10000   
16                Life expectancy at age 60 (years)  19.175239  19.34305   
17                 Life expectancy at birth (years)  70.282002  71.00000   
18  Healthy life expectancy (HALE) at birth (years)  59.192647  61.65000   
19                Life expectancy at age 60 (years)  17.935767  18.00000   
20                 Life expectancy at birth (years)  68.133069  70.36568   
21  Healthy life expectancy (HALE) at birth (years)  59.848529  63.10000   
22                Life expectancy at age 60 (years)  18.845779  18.89404   
23                 Life expectancy at birth (years)  69.880894  73.00000   
24  Healthy life expectancy (HALE) at birth (years)  58.510294  60.80000   
25                Life expectancy at age 60 (years)  17.199309  17.00000   
26                 Life expectancy at birth (years)  66.595512  69.00000   
27  Healthy life expectancy (HALE) at birth (years)  66.658491  67.40000   
28                Life expectancy at age 60 (years)  20.566757  20.11892   
29                 Life expectancy at birth (years)  75.233666  76.00000   

         min  
0   33.10000  
1   11.00000  
2   38.00000  
3   33.40000  
4   11.00000  
5   38.00000  
6   32.80000  
7   11.00000  
8   38.00000  
9   47.80000  
10  15.00000  
11  54.00000  
12  48.50000  
13  16.00000  
14  56.00000  
15  47.10000  
16  12.86658  
17  52.00000  
18  41.60000  
19  14.00000  
20  42.00000  
21  42.00000  
22  14.00000  
23  44.00000  
24  41.0

Тут мы прослеживаем, что HALE и у мужчин и у женщин очень близкий по среднему значению, что говорит нам о том, что это все складывается лишь в силу поведенческого характера мужчин, в прочем как и минимальное время жизни.

### 15

Работая лишь с общим объединенным датасетом и не используя исходную таблицу drinks, подсчитайте среднее потребление каждого вида алкоголя и среднее общее количество литров потребляемого алкоголя на человека по всем континентам. Занесите ваши результаты в отдельный датафрейм!

*Подсказка. Задача немного сложнее, чем может показаться на первый взгляд — в объединенном датасете страны встречаются разное количество раз, и из-за этого могут возникнуть определенные проблемы. Если так случится, надо подумать, как это обойти!*

*Примечание. Разумеется, это необходимо сделать автоматизированно, а не перебирая каждый континент по отдельности.*

In [182]:
unique_countries_data = df_final.drop_duplicates(subset='CountryDisplay')
continent_alcohol = unique_countries_data.groupby('RegionDisplay').agg({
    'beer_servings': 'mean',
    'spirit_servings': 'mean',
    'wine_servings': 'mean',
    'total_litres_of_pure_alcohol': 'mean'
}).reset_index()
continent_alcohol

RegionDisplay  beer_servings  spirit_servings  wine_servings  \
0                 Africa      72.609756        17.487805      16.048780   
1               Americas     144.925926       143.148148      38.962963   
2  Eastern Mediterranean      11.263158        21.578947       4.526316   
3                 Europe     179.020408       129.795918     127.346939   
4        South_East Asia      18.000000        53.777778       0.111111   
5        Western Pacific      82.136364        78.863636      27.136364   

   total_litres_of_pure_alcohol  
0                      3.314634  
1                      5.851852  
2                      0.736842  
3                      8.002041  
4                      1.288889  
5                      3.513636

Удалим дубликаты по странам, т.к значения-то там одни и теже, так как df_drinks содержит в себе каждую страну единожды и получим красивый результат.

### 16

Создание новых признаков (feature engineering) является одним из основных средств улучшения качества работы алгоритмов машинного обучения на этапе обработки данных, а также отличный способ увеличить глубину ваших выводов из проделанного анализа в целом! Частично мы с вами уже осуществляли feature engineering, когда добавляли новые столбцы в задании 13 данного раздела.

Теперь давайте добавим в таблицу столбец, который будет показывать, какое общее количество servings per person производится в среднем по стране, к которой относится научная статья. Столбец для этого признака назовите 'total_servings'.

Чем может быть полезен такой признак?

***Бонус (2 бон. балла):*** Придумайте еще какой-нибудь свой осмысленный признак, который может быть полезен для анализа (несет в себе какую-то информацию), и добавьте его в таблицу. Обязательно аргументируйте, чем полезен ваш признак.

In [183]:
df_final['total_servings'] = df_final['beer_servings'] + df_final['spirit_servings'] + df_final['wine_servings']
df_final.head()

index_x                                       GhoDisplay  \
0        0                 Life expectancy at birth (years)   
1        1  Healthy life expectancy (HALE) at birth (years)   
2        2                 Life expectancy at birth (years)   
3        3                 Life expectancy at birth (years)   
4        4                Life expectancy at age 60 (years)   

  PublishStateDisplay  YearDisplay          RegionDisplay  \
0           Published         1990               Americas   
1           Published         2012                 Europe   
2           Published         2000  Eastern Mediterranean   
3           Published         2000                 Africa   
4           Published         1990        South_East Asia   

  WorldBankIncomeGroupDisplay CountryDisplay  SexDisplay  Numeric  index_y  \
0         Lower_middle_income      Nicaragua        Male     68.0    122.0   
1                 High_income        Ireland        Male     69.3     81.0   
2                  Low_income          Yemen  Both sexes     61.0    190.0   
3         Lower_middle_income        Nigeria      Female     48.0    124.0   
4         Lower_middle_income       Thailand      Female     19.0    169.0   

     country  beer_servings  spirit_servings  wine_servings  \
0  Nicaragua           78.0            118.0            1.0   
1    Ireland          313.0            118.0          165.0   
2      Yemen            6.0              0.0            0.0   
3    Nigeria           42.0              5.0            2.0   
4   Thailand           99.0            258.0            1.0   

   total_litres_of_pure_alcohol  (Numeric, median)  \
0                           3.5               73.0   
1                          11.4               69.8   
2                           0.1               62.0   
3                           9.1               50.5   
4                           6.4               19.5   

   (total_litres_of_pure_alcohol, mean)  total_servings  
0                                   3.5           197.0  
1                                  11.4           596.0  
2                                   0.1             6.0  
3                                   9.1            49.0  
4                                   6.4           358.0

Возьму самый легкий новый признак: кол-во чистого алкоголя на заказ. То есть мы узнаем насколько в стране склонны к алкоголизму и как вообще это влияет на здоровье людей в целом. Также это отличный признак для сравнения его между регионами. Насколько вообще в разных регионах склонны к потреблению алкоголя.

In [185]:
df_final['alcohol_serving'] = df_final['total_litres_of_pure_alcohol'] / df_final['total_servings']
df_final.head()

index_x                                       GhoDisplay  \
0        0                 Life expectancy at birth (years)   
1        1  Healthy life expectancy (HALE) at birth (years)   
2        2                 Life expectancy at birth (years)   
3        3                 Life expectancy at birth (years)   
4        4                Life expectancy at age 60 (years)   

  PublishStateDisplay  YearDisplay          RegionDisplay  \
0           Published         1990               Americas   
1           Published         2012                 Europe   
2           Published         2000  Eastern Mediterranean   
3           Published         2000                 Africa   
4           Published         1990        South_East Asia   

  WorldBankIncomeGroupDisplay CountryDisplay  SexDisplay  Numeric  index_y  \
0         Lower_middle_income      Nicaragua        Male     68.0    122.0   
1                 High_income        Ireland        Male     69.3     81.0   
2                  Low_income          Yemen  Both sexes     61.0    190.0   
3         Lower_middle_income        Nigeria      Female     48.0    124.0   
4         Lower_middle_income       Thailand      Female     19.0    169.0   

     country  beer_servings  spirit_servings  wine_servings  \
0  Nicaragua           78.0            118.0            1.0   
1    Ireland          313.0            118.0          165.0   
2      Yemen            6.0              0.0            0.0   
3    Nigeria           42.0              5.0            2.0   
4   Thailand           99.0            258.0            1.0   

   total_litres_of_pure_alcohol  (Numeric, median)  \
0                           3.5               73.0   
1                          11.4               69.8   
2                           0.1               62.0   
3                           9.1               50.5   
4                           6.4               19.5   

   (total_litres_of_pure_alcohol, mean)  total_servings  alcohol_serving  
0                                   3.5           197.0         0.017766  
1                                  11.4           596.0         0.019128  
2                                   0.1             6.0         0.016667  
3                                   9.1            49.0         0.185714  
4                                   6.4           358.0         0.017877

### 17

Есть ли в данных категориальные признаки, которые принимают значения строк, а не чисел? Если да, то для многих алгоритмов это может стать серьезным препятствием, поэтому закодируйте категориальные признаки так, чтобы к данным можно было применить любые алгоритмы. Аргументируйте выбор методов кодирования.

*Подсказка. Вам могут помочь Label encoding и One-Hot Encoding. Но будьте внимательны! У каждого из этих методов есть свои сильные и слабые стороны, а также ограничения применимости.*

Воспользуемся One-Hot Encoding, что сильно увеличит размерность нашего DataFrame, но поможет нам в дальнейшем в машинном обучении. То есть мы избежим неправильной интепритации порядка категорий.

In [186]:
df_final_encoded = pd.get_dummies(df_final, columns=['CountryDisplay'])
df_final_encoded.head()

index_x                                       GhoDisplay  \
0        0                 Life expectancy at birth (years)   
1        1  Healthy life expectancy (HALE) at birth (years)   
2        2                 Life expectancy at birth (years)   
3        3                 Life expectancy at birth (years)   
4        4                Life expectancy at age 60 (years)   

  PublishStateDisplay  YearDisplay          RegionDisplay  \
0           Published         1990               Americas   
1           Published         2012                 Europe   
2           Published         2000  Eastern Mediterranean   
3           Published         2000                 Africa   
4           Published         1990        South_East Asia   

  WorldBankIncomeGroupDisplay  SexDisplay  Numeric  index_y    country  ...  \
0         Lower_middle_income        Male     68.0    122.0  Nicaragua  ...   
1                 High_income        Male     69.3     81.0    Ireland  ...   
2                  Low_income  Both sexes     61.0    190.0      Yemen  ...   
3         Lower_middle_income      Female     48.0    124.0    Nigeria  ...   
4         Lower_middle_income      Female     19.0    169.0   Thailand  ...   

   CountryDisplay_United Republic of Tanzania  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   

   CountryDisplay_United States of America  CountryDisplay_Uruguay  \
0                                        0                       0   
1                                        0                       0   
2                                        0                       0   
3                                        0                       0   
4                                        0                       0   

   CountryDisplay_Uzbekistan  CountryDisplay_Vanuatu  \
0                          0                       0   
1                          0                       0   
2                          0                       0   
3                          0                       0   
4                          0                       0   

   CountryDisplay_Venezuela (Bolivarian Republic of)  CountryDisplay_Viet Nam  \
0                                                  0                        0   
1                                                  0                        0   
2                                                  0                        0   
3                                                  0                        0   
4                                                  0                        0   

   CountryDisplay_Yemen  CountryDisplay_Zambia  CountryDisplay_Zimbabwe  
0                     0                      0                        0  
1                     0                      0                        0  
2                     1                      0                        0  
3                     0                      0                        0  
4                     0                      0                        0  

[5 rows x 212 columns]

### 18

Придумайте какое-нибудь своё интересное задание на анализ предлагаемых данных и решите его.

Креативность в этом задании приветствуется, и за нее можно получить ***1-2 бонусных балла***!

*Подсказка. Вы можете вдохновляться различными заданиями из этого ДЗ, как, например, заданиями: 4, 6, 10, 12, 14, 15, 16. Но, чтобы получить бонусные баллы, лучше не используйте аналогичные идеи, а придумайте что-то своё!*

Интересное задание на креативность заключается в том, чтобы посмотреть, сколько чистого алкоголя на заказ выпивают в различных регионах, чтобы понять какие регионы склонны к распитию более спиртных напитков.

In [195]:
continent_pure_alcohol = df_final.groupby('RegionDisplay').agg({
    'alcohol_serving': 'mean',
}).reset_index()

In [196]:
continent_pure_alcohol.head()

RegionDisplay  alcohol_serving
0                 Africa         0.053736
1               Americas         0.017874
2  Eastern Mediterranean         0.022369
3                 Europe         0.018260
4        South_East Asia         0.017572

Как мы видим, что Африка сильно выделяется на фоне остальных групп, на 3.5 процентных пункта, что свидетельствует о том, что люди в бедных странах склонны к распитию спиртного больше, не смотря на недостаток денежных средств

## Бонусная часть на анализ целевой переменной (до 5 бонусных баллов)

После всего проделанного анализа и подготовки данных мы можем перейти непосредственно к ответу на исходный вопрос исследования, который был сформулирован вами в задании 3 данного раздела.

### 19

***Бонус (5 бон. баллов):*** Дайте развернутый, обоснованный, подкрепленный данными и написанным вами кодом ответ на вопрос, влияют ли признаки зависимой таблицы на целевую переменную из главной таблицы и, если да, то каким именно образом влияют?

Обязательно аргументируйте полученные вами результаты и выводы. Чем подробнее и обоснованнее анализ вы проведете в рамках данного бонусного задания, тем больше бонусных баллов получите! Вы можете использовать подходы и методы из рассмотренных на семинаре и в рамках данного домашнего задания, а можете придумать и что-то своё. Креативность максимально приветствуется!

In [197]:
df_final.head()

index_x                                       GhoDisplay  \
0        0                 Life expectancy at birth (years)   
1        1  Healthy life expectancy (HALE) at birth (years)   
2        2                 Life expectancy at birth (years)   
3        3                 Life expectancy at birth (years)   
4        4                Life expectancy at age 60 (years)   

  PublishStateDisplay  YearDisplay          RegionDisplay  \
0           Published         1990               Americas   
1           Published         2012                 Europe   
2           Published         2000  Eastern Mediterranean   
3           Published         2000                 Africa   
4           Published         1990        South_East Asia   

  WorldBankIncomeGroupDisplay CountryDisplay  SexDisplay  Numeric  index_y  \
0         Lower_middle_income      Nicaragua        Male     68.0    122.0   
1                 High_income        Ireland        Male     69.3     81.0   
2                  Low_income          Yemen  Both sexes     61.0    190.0   
3         Lower_middle_income        Nigeria      Female     48.0    124.0   
4         Lower_middle_income       Thailand      Female     19.0    169.0   

     country  beer_servings  spirit_servings  wine_servings  \
0  Nicaragua           78.0            118.0            1.0   
1    Ireland          313.0            118.0          165.0   
2      Yemen            6.0              0.0            0.0   
3    Nigeria           42.0              5.0            2.0   
4   Thailand           99.0            258.0            1.0   

   total_litres_of_pure_alcohol  (Numeric, median)  \
0                           3.5               73.0   
1                          11.4               69.8   
2                           0.1               62.0   
3                           9.1               50.5   
4                           6.4               19.5   

   (total_litres_of_pure_alcohol, mean)  total_servings  alcohol_serving  
0                                   3.5           197.0         0.017766  
1                                  11.4           596.0         0.019128  
2                                   0.1             6.0         0.016667  
3                                   9.1            49.0         0.185714  
4                                   6.4           358.0         0.017877

In [214]:
region_stats = df_final.groupby('RegionDisplay').agg({
    'Numeric': 'median', 
    'total_litres_of_pure_alcohol': 'mean'
}).reset_index()
region_stats.head()

RegionDisplay  Numeric  total_litres_of_pure_alcohol
0                 Africa     46.0                      3.314634
1               Americas     63.5                      5.851852
2  Eastern Mediterranean     57.0                      0.736842
3                 Europe     65.9                      8.002041
4        South_East Asia     58.0                      1.288889

In [218]:
correletion = df_final[[('Numeric', 'median'), 'total_litres_of_pure_alcohol']].corr()

In [219]:
correlation

Numeric  total_litres_of_pure_alcohol
Numeric                       1.000000                      0.547582
total_litres_of_pure_alcohol  0.547582                      1.000000

Как мы видим, что явной взаимосвязи между общим количеством выпитого алкоголя и медианой по продолжительности жизни - нет, она довольно слабая, что говорит о том, что алкоголь никак не влияет на продолжительность жизни, так что можно спокойно пить и не задумываться, что умрешь в 30. В любом случае здоровье очень важно и нужно всегда помнить об этом. В Европе, как мы видим, пьют больше всех и живут дольше всех!